####################### default configuration ####################
baseURL = "https://retainitnow.com"
languageCode = "en"
title = "Retain It Now"
theme = "hargo-hugo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"

  ############# footer menu #############
  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions/"
  weight = 1

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "privacy-policy/"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact/"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/retainitnow-logo-200x182.png"
# home = "Home" # adds a Home button to the top of page
# Meta data
description = "Retain It Now"
author = "Colbal"
# google map
gmapAPI = ""
mapLatitude = ""
mapLongitude = ""
mapMarker = ""
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "1-855-LIFE-CASH"
email = "contact-us@retainitnow.com"
location = "Bend, Oregon"
# copyright
copyright = "Copyright &copy; {{< year >}} [Retain It Now](https://retainitnow.com) All Rights Reserved"

